SET FOREIGN_KEY_CHECKS = false;
DROP TABLE IF EXISTS `admin_resources`;
DROP TABLE IF EXISTS `casbin_rule`;
DROP TABLE IF EXISTS `login_attempts`;
DROP TABLE IF EXISTS `user_languages`;
DROP TABLE IF EXISTS `user_groups`;
DROP TABLE IF EXISTS `user_groups_admin_resources`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `users_user_groups`;
SET FOREIGN_KEY_CHECKS = true;
